### ISSUE TITLE
Could you please provide the training and testing process in the feature level folder?

### ISSUE THREAD

**Issue by sunshehai** [xinyuliu-jeffrey/ConsolidatedPolypDA#1]
Thank you for your contribution. Could you please provide the training and testing process in the feature level folder?  
Also, in order to read the code more easily, such as the da_faster_rcnn folder in configs and the config and data folder in maskrcnn_benchmark, is the script of the dataset in the paper missing?  Thank you.

**Comment by xinyuliu-jeffrey** [comment]
@sunshehai Hi! Thanks for your interest and sorry for the missing information. We used coco style to load the data (a dir with images and a .json file with masks, as something like here https://github.com/xinyuliu-jeffrey/ConsolidatedPolypDA/blob/a3da8eb57838235fe76ebed021bacd81c1438702/feature-level/maskrcnn_benchmark/config/paths_catalog.py#L10-L13), so we do not need to implement a new dataset or dataloader in data folder in maskrcnn_benchmark. The converted CVC and ETIS datasets are given [here](https://drive.google.com/drive/folders/1A3HEVZjWEtR3h7_SPwixDfP9oz43POhc?usp=share_link) and [here](https://drive.google.com/drive/folders/1Pq0g4n4QWg3o1oXjyBgrmjXWgyu_zWGf?usp=sharing). 
To train the model, you may simply run `python tools/train_net.py --config-file ./configs/gfda_cfg.yaml OUTPUT_DIR $YOU_OUTPUT_PATH`, and to test the model, run `python tools/test_net.py --config-file ./configs/gfda_cfg.yaml OUTPUT_DIR $YOU_OUTPUT_PATH`. You may need to modify some path that fits your environment, but just try it out first and let me know if you have remaining questions.
Sorry that I am being busy recently, and I will update the repo to provide more detailed train/test instructions. Perhaps by the end of next week. Thanks!

**Comment by sunshehai** [comment]
@xinyuliu-jeffrey Thank you for your reply. The environment I installed is as follows: python=3.6,conda install pytorch==1.4.0 torchvision==0.5.0 cudatoolkit=10.1 -c pytorch, but this environment does not apply to your code, and various errors were reported. Could you please tell me the specific environment you installed? thank you

**Comment by xinyuliu-jeffrey** [comment]
@sunshehai You may refer to the [installation in this repo](https://github.com/CityU-AIM-Group/SIGMA/blob/main/docs/INSTALL.md#installation) or the original maskrcnn-benchmark installation guide in [this repo](https://github.com/facebookresearch/maskrcnn-benchmark/blob/main/INSTALL.md#installation) for env setting.

**Comment by sunshehai** [comment]
@xinyuliu-jeffrey In feature-level>maskrcnn_benchmark>modeling>da_heads>loss.py，the da_att_cst_features.cuda() reports an error：NameError: name 'da_att_cst_features' is not defined，deleting this still doesn't solve the problem, do you know how to solve it? thank you.

**Comment by sunshehai** [comment]
Change da_att_cst_features.cuda() to da_att_features.cuda() and the following error occurs：
File "/home/hc/code2/conso/ConsolidatedPolypDA-main/feature-level/maskrcnn_benchmark/layers/consistency_loss.py", line 19, in consistency_loss
    img_fea_mean = img_fea_per_level[i].view(1, 1).repeat(intervals[i], 1)
RuntimeError: Trying to create tensor with negative dimension -511: [-511, 1]

**Comment by xinyuliu-jeffrey** [comment]
@sunshehai Fix it by changing da_att_cst_features to da_ica_cst_features. Thanks.

**Comment by sunshehai** [comment]
@xinyuliu-jeffrey Now the code can be trained, but with lots of warnings：Warning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (expandTensors at /pytorch/aten/src/ATen/native/IndexingUtils.h:20),
 the following methods will not work：import warnings      warnings.filterwarnings("ignore", category=UserWarning), 
can I only lower torch version to below 1.2? Thank you for your reply.

**Comment by xinyuliu-jeffrey** [comment]
@sunshehai This code is written with pytorch 1.1 and some functionalities have changed for higher versions of pytorch. The warnings shall not affect the results, but you may try to (1) downgrade pytorch to avoid the warnings; (2) add the warnings.filterwarnings in train_net.py and other .py files that may cause this warning; (3) find the tensor that raises the warning and add .bool() after it.

**Comment by sunshehai** [comment]
@xinyuliu-jeffrey  Thank you for your prompt and patient reply. I would like to ask you the following questions：

1.In the training with your dataset, the index APs=-1.0, and your paper did not mention the index APs, what is the reason? In my dataset，index is normal, but the precision is low，my dataset ap50=0.36, ap=0.0996, ap75=0.0211,aps=0.03.
2.In the log.txt of training results, there is no rule for the indicator loss，how do you see if the model converges according to the log.txt indexes? In addition, how to modify the superparameter in file gfda_cfg.yaml to improve the accuracy of the model on other datasets? Did you get the superparameter by experiment or have any experience?
3.In code "scale-aware domain adaptive faster rcnn", the accuracy of ap50 in my dataset for the first several times was 61/63 respectively, but recently the accuracy was 44/53, and nothing was changed. Have you ever encountered such a situation?

Thank you very much for your reply.

**Comment by xinyuliu-jeffrey** [comment]
Hi @sunshehai ,

> the index APs=-1.0
APs refers to AP for small objects: area < 32^2 [refer to official coco eval metric](https://cocodataset.org/#detection-eval). The target dataset we used do not have objects in this size range, so it will have -1.0 for all methods thus it is unnecessary to report this metric.

> index is normal, but the precision is low
The performance depends on your dataset, AP50=0.36 shall give somewhat recognizable detection results, you may visualize it and see if the model learns something. However, the AP and AP75 are low, so I conjecture the object in your dataset may be hard to localize, so the predicted boxes have small iou with the GT.

> how do you see if the model converges
I am not sure about the meaning of "indicator loss" you mentioned. If you refer to the adversarial losses for adaptation, they could fluctuate during training and we are not capable identify when the model "converges" according to the loss in the adversarial training scheme [more explanation can be found here](https://datascience.stackexchange.com/questions/82854/should-discriminator-loss-increase-or-decrease). Selecting a best-performed domain adaptative detection model is always difficult [see this issue](https://github.com/CityU-AIM-Group/SIGMA/issues/12#issuecomment-1187113761), so you may either validate the performance of your model frequently and select the best performed one, or do early stopping at a specific iteration (we use 30k iter here).

> how to modify the superparameter in file gfda_cfg.yaml
It depends on your data. We use most parameters in [official maskrcnn-benchmark repo](https://github.com/facebookresearch/maskrcnn-benchmark). Note that the ROI_BOX_HEAD.NUM_CLASSES should be set correct for your dataset.

> In code "scale-aware domain adaptive faster rcnn", the accuracy of ap50 in my dataset for the first several times was 61/63 respectively, but recently the accuracy was 44/53
I am not sure about it, but there may be some possibilities: (1) Adversarial training is unstable as I just mentioned, so it may be just fluctuation. (2) Data may have changed. (3) The codebase was modified accidentally. (4) The environment is changed. You may raise an issue in that repo and provide more details. e.g., provide the logs.

Hope this clarifies.

Best,
Xinyu

**Comment by sunshehai** [comment]
@xinyuliu-jeffrey 
In my single class ship dataset, I trained with your code, and there was no change in the code before and after the two training sessions. The accuracy ap50 of the first session was 0.54, and the accuracy ap50 of the second session was 0.46. Could you please tell me how to ensure the reproducibility of the results each time? Thank you. I didn't fix it with random seeds.  The following are my training logs:
[log1.txt](https://github.com/xinyuliu-jeffrey/ConsolidatedPolypDA/files/11166238/log1.txt)
[log2.txt](https://github.com/xinyuliu-jeffrey/ConsolidatedPolypDA/files/11166240/log2.txt)

In order to ensure the reproducibility of the results each time. Should I select the best model according to SIGMA paper or use the early stop method? In your paper, does the early stop method stop the training at 30k iterations and use the training weight at 30k to evaluate the indicators of the test set? (The dataset is only divided into two parts: training and testing, without verification set.) However, in this way, it cannot be guaranteed that the two training models before and after will reach the optimum in 30k iterations, and the maximum number of iterations in your code is 60k, there is no code related to early stop method, if there is, could you please provide it? Thank you for your reply.

**Comment by xinyuliu-jeffrey** [comment]
@sunshehai I've went through your logs and it is obvious that the final loss in log1 is smaller than log2 (0.0668 vs 0.0685), so the performance difference is expected. As you said, random seed, data augmentation, worker_init_fn, etc. could all cause the performance fluctuation. You may try the solutions [here](https://pytorch.org/docs/stable/notes/randomness.html). 

I also notice your test set has 232 images, which is not a quite large dataset so the overall AP could also vary if only one image has a poor detection result. You may try a larger dataset for testing, or print your results on your train set, to see if they also have a large performance gap for multiple runs as a reference.

**Comment by sunshehai** [comment]
@xinyuliu-jeffrey 
Hello, I did not find the program about early stop method in your code, could you please provide it? So that the program can automatically select the appropriate number of iterations based on the data. Thank you.

**Comment by xinyuliu-jeffrey** [comment]
@sunshehai Sorry for the confusion caused by my previous response. You may simply change https://github.com/xinyuliu-jeffrey/ConsolidatedPolypDA/blob/933b0735e85dad2a37f8b4072192c85743a10e6e/feature-level/configs/gfda_cfg.yaml#L47 to 30000 to early stop your training at 30000 iterations.

**Comment by sunshehai** [comment]
@xinyuliu-jeffrey 
Thank you very much for your reply. May I ask on what basis did you choose this 30000 iteration? In my own data set, the basic highest accuracy also appeared at 30000 iterations, and occasionally at 32,500 iterations.

**Comment by sunshehai** [comment]
Or according to several experiments, it is better to stop early at 30,000 times?

**Comment by xinyuliu-jeffrey** [comment]
@sunshehai Just an empirical choice. I've tested models saved at different iterations, and found the models after 30000 iterations do not show much significant improvement. So I choose 30000 for a trade-off between performance and training time. You may also test your models saved at different iterations to select the best number of max iterations.
