### ISSUE TITLE
The running process of the program

### ISSUE THREAD

**Issue by gaosantai** [xinyuliu-jeffrey/ConsolidatedPolypDA#2]
Hello, may I know when will the README file be updated? If it is not possible for now, could you please briefly describe the running process of the feature-level file? Thank you! Your code has been very helpful for my work.

**Comment by xinyuliu-jeffrey** [comment]
Hi @gaosantai , Thanks for your interest in our work!

For the training/eval process, please kindly refer to https://github.com/xinyuliu-jeffrey/ConsolidatedPolypDA/issues/1#issuecomment-1466279854. Please feel free to contact me if you have other questions.

**Comment by gaosantai** [comment]
Hello, after the second stage of feature level processing, currently only one quantitative result can be seen, and no qualitative result can be seen. My current research direction is to standardize two types of endoscopic images from different sources. How can I see the visualization results after the second stage of image processing? Thank you!


Best wishes!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xinyuliu-jeffrey/ConsolidatedPolypDA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月29日(星期二) 晚上6:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xinyuliu-jeffrey/ConsolidatedPolypDA] The running process of the program (Issue #2)





 
Closed #2 as completed.
